name: Monitor NY Events

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests

      - name: Show last_updates.json before script
        run: |
          echo 'Conteúdo de last_updates.json antes do script:'
          cat last_updates.json || echo '{}'

      - name: Run notifier
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: python notifier.py

      - name: Show last_updates.json after script
        run: |
          echo 'Conteúdo de last_updates.json depois do script:'
          cat last_updates.json || echo '{}'

      - name: Commit and push state files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add last_updates.json
          git diff --staged --quiet || git commit -m "chore: update 1iota state [skip ci]"
          git push
