name: Monitor NYCC Panels

on:
  schedule:
    - cron: '0 3 * * *'  # Executa diariamente às 03:00 UTC
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Check date
        run: |
          TODAY=$(date -u +"%Y-%m-%d")
          if [[ "$TODAY" > "2025-10-13" ]]; then
            echo "Data limite atingida. Workflow não será mais executado."
            exit 0
          fi

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests

      - name: Show last_updates_nycc.json before script
        run: |
          echo 'Conteúdo de last_updates_nycc.json antes do script:'
          cat last_updates_nycc.json || echo '{}'

      - name: Run NYCC notifier
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: python nycc_notifier.py

      - name: Show last_updates_nycc.json after script
        run: |
          echo 'Conteúdo de last_updates_nycc.json depois do script:'
          cat last_updates_nycc.json || echo '{}'

      - name: Commit and push state files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add last_updates_nycc.json
          git diff --staged --quiet || git commit -m "chore: update NYCC state [skip ci]"
          git push
